import type { FunnelStep } from "./types";

export const FUNNEL_STEPS: FunnelStep[] = [
  { id: "landing", phase: "hook", type: "interstitial", title: "Eat without fear again.",
    subtitle: "A 2-minute quiz builds your personal relief plan: find your trigger foods, calm your nights, stop guessing.",
    cta: "Start my quiz" },
  { id: "age", phase: "about", type: "select", title: "How old are you?",
    options: [{ value: "u30", label: "Under 30" }, { value: "30-44", label: "30-44" }, { value: "45-59", label: "45-59" }, { value: "60+", label: "60+" }] },
  { id: "sex", phase: "about", type: "select", title: "What is your sex?", subtitle: "Reflux patterns differ; this tunes your plan.",
    options: [{ value: "female", label: "Female" }, { value: "male", label: "Male" }, { value: "na", label: "Prefer not to say" }] },
  { id: "hear_about", phase: "about", type: "select", title: "Where did you hear about GERDBuddy?", subtitle: "Helps us reach more people who need relief.",
    options: [{ value: "google", label: "Google search" }, { value: "app_store", label: "App Store" }, { value: "ai", label: "AI assistant (ChatGPT, etc.)" }, { value: "reddit", label: "Reddit or a forum" }, { value: "friend", label: "Friend or family" }, { value: "social", label: "Social media" }, { value: "other", label: "Other" }] },
  { id: "duration", phase: "about", type: "select", title: "How long have you been dealing with reflux?",
    options: [{ value: "weeks", label: "A few weeks" }, { value: "months", label: "A few months" }, { value: "years", label: "1-5 years" }, { value: "5plus", label: "More than 5 years" }] },
  { id: "frequency", phase: "about", type: "select", title: "How often does it hit?",
    options: [{ value: "monthly", label: "A few times a month" }, { value: "weekly", label: "A few times a week" }, { value: "daily", label: "Daily" }, { value: "multi", label: "Multiple times a day" }] },
  { id: "severity", phase: "about", type: "select", title: "When it hits, how bad is it usually?",
    options: [{ value: "annoying", label: "Annoying" }, { value: "disruptive", label: "Disruptive" }, { value: "ruins", label: "It ruins my day" }, { value: "scares", label: "It scares me" }] },
  { id: "timing", phase: "about", type: "select", title: "When is it worst?",
    options: [{ value: "after_meals", label: "Right after meals" }, { value: "evening", label: "Evenings" }, { value: "night", label: "Middle of the night" }, { value: "random", label: "Random, no pattern I can see" }] },
  { id: "nights", phase: "cost", type: "slider", title: "How many nights a week does reflux wake you or keep you up?", subtitle: "Be honest.", min: 0, max: 7, unit: "nights" },
  { id: "spend", phase: "cost", type: "slider", title: "What do you spend per month managing it?", subtitle: "Antacids, prescriptions, the safe-food workarounds.", min: 0, max: 100, unit: "$" },
  { id: "loss_stat", phase: "cost", type: "stat", title: "At this rate, that is {nightsPerYear} rough nights and ${dollarsPerYear} a year.", subtitle: "Every year, until the pattern changes.", cta: "There is a better way" },
  { id: "hope", phase: "cost", type: "interstitial", title: "The good news: reflux has patterns.",
    subtitle: "Most GERDBuddy users spot their first trigger within the first week of logging. Yours are probably hiding in plain sight.", cta: "Find mine" },
  { id: "symptoms", phase: "triggers", type: "multi", title: "Which symptoms do you know too well?",
    options: [{ value: "heartburn", label: "Heartburn" }, { value: "regurg", label: "Regurgitation" }, { value: "chest", label: "Chest pressure" }, { value: "cough", label: "Chronic cough or throat clearing" }, { value: "bloat", label: "Bloating" }, { value: "nausea", label: "Nausea" }] },
  { id: "fear_foods", phase: "triggers", type: "multi", title: "Which foods feel like a gamble?",
    options: [{ value: "coffee", label: "Coffee" }, { value: "spicy", label: "Spicy food" }, { value: "tomato", label: "Tomatoes and sauces" }, { value: "chocolate", label: "Chocolate" }, { value: "alcohol", label: "Alcohol" }, { value: "fried", label: "Fried food" }, { value: "citrus", label: "Citrus" }, { value: "bread", label: "Bread and gluten" }] },
  { id: "tried", phase: "triggers", type: "multi", title: "What have you tried so far?",
    options: [{ value: "antacids", label: "Antacids" }, { value: "ppi", label: "PPIs or H2 blockers" }, { value: "cutting", label: "Cutting foods at random" }, { value: "propped", label: "Sleeping propped up" }, { value: "doctor", label: "Doctor visits" }, { value: "nothing", label: "Nothing consistent" }] },
  { id: "meds", phase: "triggers", type: "select", title: "Do you take reflux medication today?",
    options: [{ value: "daily", label: "Daily" }, { value: "sometimes", label: "Sometimes" }, { value: "no", label: "No" }, { value: "less", label: "Yes, and I want to need less of it" }] },
  { id: "pattern_demo", phase: "proof", type: "interstitial", title: "Here is how GERDBuddy finds YOUR triggers.",
    subtitle: "You log meals and symptoms. GERDBuddy cross-references timing, ingredients, and severity to isolate your personal triggers, not a generic avoid-everything list. The scanner reads menus and labels so eating out stops being a gamble.", cta: "Show me" },
  { id: "reviews", phase: "proof", type: "interstitial", title: "People like you, eating like themselves again.",
    subtitle: "\"I was very pleased with how much this app improved my symptoms. I went in with very low expectations after hearing about it a few times, but now I am pleasantly surprised. Thanks!\" - creisert\nREAL REVIEWS NEEDED\nREAL REVIEWS NEEDED",
    cta: "Continue" },
  { id: "trust", phase: "proof", type: "interstitial", title: "Your answers stay yours.",
    subtitle: "Your logs live on your device. Your account exists so your plan is waiting when you open the app.", cta: "Continue" },
  { id: "goal", phase: "commitment", type: "select", title: "What would relief mean for you?",
    options: [{ value: "sleep", label: "Sleeping through the night" }, { value: "coffee", label: "Coffee without consequences" }, { value: "eatout", label: "Eating out without an escape plan" }, { value: "meds", label: "Fewer pills" }, { value: "all", label: "All of it" }] },
  { id: "name", phase: "commitment", type: "text", title: "What should we call you?", subtitle: "Your plan is personal. It should sound like it.", cta: "Continue" },
  { id: "building", phase: "commitment", type: "interstitial", title: "Building your relief plan...", autoAdvanceMs: 2600 },
  { id: "plan_reveal", phase: "commitment", type: "plan", title: "{name}, here is your first week", cta: "I am ready" },
  { id: "account", phase: "convert", type: "account", title: "Save your plan", subtitle: "Your plan and progress will be waiting in the app." },
  { id: "paywall", phase: "convert", type: "paywall", title: "Try GERDBuddy Pro for $0.00", subtitle: "3-day free trial, then $39.99/year ($0.76/week). Cancel anytime." },
  { id: "success", phase: "convert", type: "success", title: "You are in, {name}.", subtitle: "Download the app and sign in with the email you just used." },
];

export const STEP_IDS = FUNNEL_STEPS.map((s) => s.id);
