import { useCallback, useState } from "react";
import { Image, Text, View, Share } from "react-native";
import { useFocusEffect } from "@react-navigation/native";
import { Clock, TrendingDown, Calendar, Share2, FileText } from "lucide-react-native";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import Screen from "../components/Screen";
import Card from "../components/Card";
import ProTeaser from "../components/ProTeaser";
import Button from "../components/Button";
import { getMeals, getSymptoms, getUser } from "../services/storage";
import { generateTriggerReport } from "../utils/triggerEngine";
import { showToast } from "../utils/feedback";
import { usePremiumStatus } from "../hooks/usePremiumStatus";

const turtleSad = require("../assets/mascot/turtle_sad.png");

const confidenceLabel = (c) => c > 0.7 ? "High" : c >= 0.5 ? "Medium" : "Low";

const buildReportHtml = (report) => {
  const date = new Date(report.generatedAt).toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });

  const triggerRows = report.topTriggers.length > 0
    ? report.topTriggers.map((t, i) => `
        <tr class="${i % 2 ? "alt" : ""}">
          <td>${t.ingredient}</td>
          <td>${t.symptomRate}%</td>
          <td>${t.avgSeverity}/5</td>
          <td>${confidenceLabel(t.confidence)}</td>
          <td>${t.totalOccurrences}</td>
        </tr>`).join("")
    : '<tr><td colspan="5" style="text-align:center;color:#888;">No triggers identified yet</td></tr>';

  const safeRows = report.safeFoods.length > 0
    ? report.safeFoods.map((f, i) => `
        <tr class="${i % 2 ? "alt" : ""}">
          <td>${f.ingredient}</td>
          <td>${f.safetyScore}%</td>
          <td>${f.totalOccurrences}</td>
          <td>${f.symptomFreeOccurrences}</td>
        </tr>`).join("")
    : '<tr><td colspan="4" style="text-align:center;color:#888;">Not enough data yet</td></tr>';

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  body { font-family: -apple-system, Helvetica, Arial, sans-serif; padding: 32px; color: #1f2a30; }
  h1 { font-size: 22px; color: #3aa27f; margin-bottom: 4px; }
  h2 { font-size: 16px; margin-top: 28px; border-bottom: 2px solid #3aa27f; padding-bottom: 4px; }
  .meta { font-size: 12px; color: #888; margin-bottom: 24px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; margin-top: 8px; }
  th { background: #3aa27f; color: #fff; text-align: left; padding: 8px; }
  td { padding: 8px; border-bottom: 1px solid #e5e7eb; }
  tr.alt { background: #f9fafb; }
  .overview { display: flex; gap: 16px; margin-top: 8px; }
  .stat { flex: 1; background: #f3f4f6; border-radius: 8px; padding: 16px; text-align: center; }
  .stat-value { font-size: 28px; font-weight: bold; }
  .stat-label { font-size: 11px; color: #888; margin-top: 4px; }
  .footer { margin-top: 32px; font-size: 10px; color: #aaa; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 12px; }
</style></head>
<body>
  <h1>GERD Buddy Health Report</h1>
  <p class="meta">Generated ${date}</p>

  <h2>Overview</h2>
  <div class="overview">
    <div class="stat"><div class="stat-value">${report.totalMeals}</div><div class="stat-label">Meals Logged</div></div>
    <div class="stat"><div class="stat-value">${report.totalSymptoms}</div><div class="stat-label">Symptoms</div></div>
    <div class="stat"><div class="stat-value">${report.avgSeverity}/5</div><div class="stat-label">Avg Severity</div></div>
    <div class="stat"><div class="stat-value">${report.symptomFreeDays}</div><div class="stat-label">Symptom-Free Days</div></div>
  </div>

  <h2>Top Triggers</h2>
  <table>
    <tr><th>Food</th><th>Symptom Rate</th><th>Avg Severity</th><th>Confidence</th><th>Times Eaten</th></tr>
    ${triggerRows}
  </table>

  <h2>Safe Foods</h2>
  <table>
    <tr><th>Food</th><th>Safety Score</th><th>Times Eaten</th><th>Symptom-Free</th></tr>
    ${safeRows}
  </table>

  <div class="footer">Generated by GERD Buddy. This is not a medical diagnosis. Please consult your doctor.</div>
</body>
</html>`;
};

export default function ReportScreen() {
  const [patternReport, setPatternReport] = useState(null);
  const [userId, setUserId] = useState(null);
  const { isPro, refreshStatus } = usePremiumStatus(userId);

  const loadData = useCallback(async () => {
    try {
      const [meals, symptoms, user] = await Promise.all([
        getMeals(), getSymptoms(), getUser(),
      ]);
      if (user?.id) setUserId(user.id);
      setPatternReport(generateTriggerReport(meals, symptoms));
    } catch (error) {
      console.warn("Failed to load report data", error);
    }
  }, []);

  useFocusEffect(
    useCallback(() => {
      loadData();
      refreshStatus();
    }, [loadData, refreshStatus])
  );

  const handleShare = async () => {
    const text = patternReport
      ? `My GERDBuddy patterns:\n\n${patternReport.topTriggers
          .slice(0, 3)
          .map((t, i) => `${i + 1}. ${t.ingredient}`)
          .join("\n")}\n\nAvg severity: ${patternReport.avgSeverity}/5\nSymptom-free days: ${patternReport.symptomFreeDays}`
      : "I'm using GERDBuddy to track my digestive health.";
    try {
      await Share.share({ title: "My GERDBuddy Patterns", message: text });
    } catch (error) {
      showToast("Unable to share", error.message);
    }
  };

  const handleSharePDF = async () => {
    if (!patternReport) return;
    try {
      const html = buildReportHtml(patternReport);
      const { uri } = await Print.printToFileAsync({ html });
      await Sharing.shareAsync(uri, {
        mimeType: "application/pdf",
        dialogTitle: "Share GERD Buddy Report",
        UTI: "com.adobe.pdf",
      });
    } catch (error) {
      showToast("Unable to generate PDF", error.message);
    }
  };

  if (!patternReport) {
    return (
      <Screen contentClassName="items-center justify-center gap-4">
        <Image source={turtleSad} style={{ width: 100, height: 100 }} resizeMode="contain" />
        <Text className="text-sm text-muted-foreground text-center">
          Log meals and symptoms to see your report.
        </Text>
      </Screen>
    );
  }

  return (
    <Screen contentClassName="gap-5">
      {/* Overview counts */}
      <View className="flex-row gap-3">
        <Card className="flex-1 p-4 items-center">
          <Text className="text-3xl font-bold text-foreground">{patternReport.totalMeals}</Text>
          <Text className="text-xs text-muted-foreground mt-1">Meals</Text>
        </Card>
        <Card className="flex-1 p-4 items-center">
          <Text className="text-3xl font-bold text-accent">{patternReport.totalSymptoms}</Text>
          <Text className="text-xs text-muted-foreground mt-1">Symptoms</Text>
        </Card>
      </View>

      {/* Stats grid */}
      {isPro ? (
        <View className="flex-row flex-wrap gap-3">
          <Card className="p-4 basis-[48%] items-center">
            <Clock size={18} color="#5f6f74" />
            <Text className="text-2xl font-bold text-accent mt-2">{patternReport.lateEatingRisk}%</Text>
            <Text className="text-xs text-muted-foreground mt-1">Late eating</Text>
          </Card>
          <Card className="p-4 basis-[48%] items-center">
            <TrendingDown size={18} color="#5f6f74" />
            <Text className="text-2xl font-bold text-foreground mt-2">{patternReport.avgSeverity}/5</Text>
            <Text className="text-xs text-muted-foreground mt-1">Avg severity</Text>
          </Card>
          <Card className="p-4 basis-[48%] items-center">
            <Calendar size={18} color="#5f6f74" />
            <Text className="text-2xl font-bold text-success mt-2">{patternReport.symptomFreeDays}</Text>
            <Text className="text-xs text-muted-foreground mt-1">Symptom-free days</Text>
          </Card>
          <Card className="p-4 basis-[48%] items-center">
            <Clock size={18} color="#5f6f74" />
            <Text className="text-xl font-bold text-foreground mt-2">{patternReport.worstTimeOfDay}</Text>
            <Text className="text-xs text-muted-foreground mt-1">Peak symptom time</Text>
          </Card>
        </View>
      ) : (
        <ProTeaser
          title="Unlock analytics"
          description="See severity trends, timing patterns, and symptom-free days."
        />
      )}

      {isPro && (
        <View className="gap-3">
          <Button onPress={handleSharePDF} variant="primary" className="w-full flex-row gap-2">
            <FileText size={18} color="#ffffff" />
            <Text className="text-white font-semibold">Share with Doctor</Text>
          </Button>
          <Button onPress={handleShare} variant="outline" className="w-full flex-row gap-2">
            <Share2 size={18} color="#1f2a30" />
            <Text className="text-foreground font-semibold">Share as Text</Text>
          </Button>
        </View>
      )}

      <Text className="text-[10px] text-muted-foreground text-center">
        Patterns, not diagnoses. Consult your doctor.
      </Text>
    </Screen>
  );
}
